### ISSUE TITLE
Zoom in 후 차트 클릭시 Zoom 이 풀리는 문제

### ISSUE THREAD

**Issue by Seo0H** [wanted-onboarding-10team/pre-onboarding-9th-3-10#51]

**Comment by Ryong-E** [comment]
Brush에 인덱스 변경시 State값 변경 이벤트가 누락되어있습니다
Brush에 startIndex,endIndex의 값이 설정되어있지않아서 렌더링시에 초기값으로 설정되어서 Zoom이 풀립니다
